### ISSUE TITLE
Write what's script doing now.

### ISSUE THREAD

**Issue by AChep** [Pastafarianist/vk-music-organizer#1]
Write what's script doing now, like "Downloading albums list...".

**Comment by stovberpv** [comment]
Traceback (most recent call last):
  File "D:\vk-music-organizer-master\vk_music_organizer.py", line 218, in <module>
    main(email=email, password=password)
  File "D:\vk-music-organizer-master\vk_music_organizer.py", line 212, in main
    if result[0]['aid'] != audios[0]['aid']:
IndexError: list index out of range
